### PR TITLE
Reduce memory churn and copy while decoding large payload

### PR DESCRIPTION
**Pull request by bdraco**
I was testing with some cameras and noticed the image encryption overhead was showing up in the profile

- Implement the todo to not return `False`

### CODE REVIEW

**Comment by bdraco** [comment]
I thought it was caused by this PR, but pressing identify on the eve energy causes a disconnect

Happens on main as well

**Comment by bdraco** [comment]
problem was with the esp32 but this code

**Comment by bdraco** [comment]
coap uses cryptography directly so no changes there

**Review by Jc2k — APPROVED** [review]

**Comment by Jc2k** [comment]
😍 for getting rid of that return false.

**Comment by bdraco** [comment]
thanks

**Pull request merged**
