### PR TITLE
Do not reuse BleakClient per bleak authors recommendation

### PR DESCRIPTION
**Pull request by bdraco**
- Also fixes missed state changes

### CODE REVIEW

**Comment by bdraco** [comment]
Looks like we can drop the double timeout now that we pass `BLEDevice` since it will never get into the discovery which can double the timeout

**Comment by bdraco** [comment]
dare I say that its stable on linux now

**Comment by bdraco** [comment]
I haven't had one failure to connect / put and I've been abusing it as much as possible for 20 minutes with these changes

**Review by Jc2k — APPROVED** [review]

**Comment by bdraco** [comment]
Retest after letting it sit for a while looks good. Still reconnects 👍

**Comment by bdraco** [comment]
Will push a release and bump hass in a few

**Pull request merged**
