### PR TITLE
Fix naming backwards compat

### PR DESCRIPTION
**Pull request by bdraco**

### CODE REVIEW

**Comment by bdraco** [comment]
Down to 7 tests failing
```
       7 failed
         - tests/components/homekit_controller/test_config_flow.py:480 test_discovery_already_configured_update_csharp[pyloop]
         - tests/components/homekit_controller/test_diagnostics.py:18 test_config_entry[pyloop]
         - tests/components/homekit_controller/test_diagnostics.py:285 test_device[pyloop]
         - tests/components/homekit_controller/test_init.py:49 test_async_remove_entry[pyloop]
         - tests/components/homekit_controller/test_init.py:101 test_offline_device_raises[pyloop]
         - tests/components/homekit_controller/test_storage.py:67 test_storage_is_updated_on_add[pyloop]
         - tests/components/homekit_controller/specific_devices/test_ecobee3.py:220 test_ecobee3_add_sensors_at_runtime[pyloop]
```

**Comment by bdraco** [comment]
All tests passing now

**Review by Jc2k — APPROVED** [review]

**Comment by bdraco** [comment]
Should probably change the default to squash 👀

**Comment by Jc2k** [comment]
Haha! It is in my client so I don't notice lol.

**Pull request merged**
