### PR TITLE
Subscribe/Unsubscribe one accessory at a time

### PR DESCRIPTION
**Pull request by bdraco**
https://github.com/Jc2k/aiohomekit/pull/31 changed the behavior to subscribe to one char at a time for subscribe.  That's really inefficient, but closer to iOS.

This PR takes a more efficient approach which is to subscribe/unsubscribe by doing the one call per accessory id at a time which matches iOS 14.6 behavior.

### CODE REVIEW

**Comment by bdraco** [comment]
Tested with a smart bar and a myq bridge 👍

**Comment by bdraco** [comment]
Tested with a heated floor TH1310WF thermostat 👍

**Comment by bdraco** [comment]
Tested with Tado Smart AC Control 👍

**Review by Jc2k — APPROVED** [review]
Nice 👍

**Pull request merged**
