### PR TITLE
fix: linked services for ble transport

### PR DESCRIPTION
**Pull request by bdraco**
Screenshot 2022-10-28 at 3 37 12 PM

```
2022-10-28 15:37:48.129 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Wemo Stage 063 [BA9296B7-6899-8669-F3B5-C0689672DA5A] (id=E4:B3:1A:7A:D3:5D): Trying state_num 4 for encrypted notification: HomeKitEncryptedNotification(name='Wemo Stage 063', address='BA9296B7-6899-8669-F3B5-C0689672DA5A', id='e4:b3:1a:7a:d3:5d', advertising_identifier=b'\xe4\xb3\x1az\xd3]', encrypted_payload=b"Hw\x94~d\tz'Asw\xb4\xb1\x10\xfa\x94")
2022-10-28 15:37:48.130 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Wemo Stage 063 [BA9296B7-6899-8669-F3B5-C0689672DA5A] (id=E4:B3:1A:7A:D3:5D): Received notification: encrypted =  b"Hw\x94~d\tz'Asw\xb4\xb1\x10\xfa\x94" - decrypted = bytearray(b'\x04\x00C\x00\x00\x00\x00\x00\x00\x00\x00\x00') - gsn=4 - iid=67 - value=bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00')
2022-10-28 15:37:48.130 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Wemo Stage 063 [BA9296B7-6899-8669-F3B5-C0689672DA5A] (id=E4:B3:1A:7A:D3:5D): Received notification: results = {(1, 67): {'value': 0}}
2022-10-28 15:37:48.134 INFO (MainThread) [homeassistant.components.automation.wemo] wemo: Running automation actions
2022-10-28 15:37:48.135 INFO (MainThread) [homeassistant.components.automation.wemo] wemo: Executing step call service
2022-10-28 15:38:08.136 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Wemo Stage 063 [BA9296B7-6899-8669-F3B5-C0689672DA5A] (id=E4:B3:1A:7A:D3:5D): Trying state_num 5 for encrypted notification: HomeKitEncryptedNotification(name='Wemo Stage 063', address='BA9296B7-6899-8669-F3B5-C0689672DA5A', id='e4:b3:1a:7a:d3:5d', advertising_identifier=b'\xe4\xb3\x1az\xd3]', encrypted_payload=b'\x85\x17\xcf\xa7\xec\xce\xbf\xad\xbdIs\x88\xf6\xdfnm')
2022-10-28 15:38:08.136 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Wemo Stage 063 [BA9296B7-6899-8669-F3B5-C0689672DA5A] (id=E4:B3:1A:7A:D3:5D): Received notification: encrypted =  b'\x85\x17\xcf\xa7\xec\xce\xbf\xad\xbdIs\x88\xf6\xdfnm' - decrypted = bytearray(b'\x05\x00C\x00\x00\x00\x00\x00\x00\x00\x00\x00') - gsn=5 - iid=67 - value=bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00')
2022-10-28 15:38:08.136 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Wemo Stage 063 [BA9296B7-6899-8669-F3B5-C0689672DA5A] (id=E4:B3:1A:7A:D3:5D): Received notification: results = {(1, 67): {'value': 0}}
2022-10-28 15:38:08.141 INFO (MainThread) [homeassistant.components.automation.wemo] wemo: Running automation actions
2022-10-28 15:38:08.142 INFO (MainThread) [homeassistant.components.automation.wemo] wemo: Executing step call service

```

### CODE REVIEW

**Review by Jc2k — COMMENTED** [review]
I think this is on the service not the char.

**Comment by bdraco** [comment]
lol, that makes more sense 👍

**Comment by bdraco** [comment]
The HAP service should include an optional ”Service Signature” HAP characteristic with UUID 000000A5-0000- 1000-8000-0026BB765291

**Comment by bdraco** [comment]
So it actually is on a char, but there is a specific char for the service

**Comment by Jc2k** [comment]
Ah!

**Comment by bdraco** [comment]
So we need to read that char and then merge the data into the service that its on

**Comment by Jc2k** [comment]
What about something like:

```
diff --git a/aiohomekit/controller/ble/pairing.py b/aiohomekit/controller/ble/pairing.py
index d83f7ca..5fc65e7 100644
--- a/aiohomekit/controller/ble/pairing.py
+++ b/aiohomekit/controller/ble/pairing.py
@@ -85,6 +85,7 @@ NEVER_TIME = -AVAILABILITY_INTERVAL
 
 
 SERVICE_INSTANCE_ID = "E604E95D-A759-4817-87D3-AA005083A0D1"
+SERVICE_SIGNATURE = "000000A5-0000- 1000-8000-0026BB765291"
 
 
 SUBSCRIPTION_RESTORE_DELAY = 0.5
@@ -419,6 +420,10 @@ class BlePairing(AbstractPairing):
                 if normalize_uuid(char.uuid) == SERVICE_INSTANCE_ID:
                     continue
 
+                if normalize_uuid(char.uuid) == SERVICE_SIGNATURE and char.linked_services:
+                    s.linked = char.linked_services
+                    continue
+
                 iid = await self.client.get_characteristic_iid(char)
                 if iid is None:
                     logger.debug("%s: No iid for %s", self.name, char.uuid)
diff --git a/aiohomekit/controller/ble/structs.py b/aiohomekit/controller/ble/structs.py
index e2cf477..bee31b5 100644
--- a/aiohomekit/controller/ble/structs.py
+++ b/aiohomekit/controller/ble/structs.py
@@ -305,7 +305,4 @@ class Characteristic(TLVStruct):
             result["minValue"] = min_max_value[0]
             result["maxValue"] = min_max_value[1]
 
-        if self.linked_services:
-            result["linked"] = self.linked_services
-
         return result
```

(Can't test because my Wemo Stage is brain dead).

**Comment by bdraco** [comment]
> (Can't test because my Wemo Stage is brain dead).

I'm going to reset the one I bought and mail it to you

**Comment by bdraco** [comment]
its still only subscribing to button 1 though for broadcasted encrypted events

**Review by Jc2k — APPROVED** [review]

**Pull request merged**
