### PR TITLE
Ensure we resolve services again after the debounce timeout

### PR DESCRIPTION
**Pull request by bdraco**
Since we held on to the AsyncServiceInfo for as long as the service was alive, we never respected the TTL of the DNSAddress records which meant we effectively held on to them forever as long as the device was on the network

related issue https://github.com/home-assistant/core/issues/86029

### CODE REVIEW

**Review by Jc2k — APPROVED** [review]

**Comment by bdraco** [comment]
trace looks good

_async_resolve_later
_handle_service

**Comment by bdraco** [comment]
TODO 

- [ ] change ip of switchbot plug and make sure its picked up

**Comment by bdraco** [comment]
verified ip change works on switchbot plug mini

**Comment by bdraco** [comment]
no errors in the log on restart, works again on restart

**Pull request merged**
