### PR TITLE
Fix set changed during iteration during subscriptions

### LINKED ISSUE #85: RuntimeError: Set changed size during iteration
```
2022-05-09 19:41:59 ERROR (MainThread) [aiohomekit.controller.ip.connection] Unexpected error whilst trying to connect to accessory. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohomekit/controller/ip/connection.py", line 540, in _reconnect
    return await self._connect_once()
  File "/usr/local/lib/python3.9/site-packages/aiohomekit/controller/ip/connection.py", line 648, in _connect_once
    await self.owner.connection_made(True)
  File "/usr/local/lib/python3.9/site-packages/aiohomekit/controller/ip/pairing.py", line 103, in connection_made
    await self.subscribe(self.subscriptions)
  File "/usr/local/lib/python3.9/site-packages/aiohomekit/controller/ip/pairing.py", line 299, in subscribe
    return await self._update_subscriptions(characteristics, True)
  File "/usr/local/lib/python3.9/site-packages/aiohomekit/controller/ip/pairing.py", line 330, in _update_subscriptions
    "characteristics": [
  File "/usr/local/lib/python3.9/site-packages/aiohomekit/controller/ip/pairing.py", line 330, in <listcomp>
    "characteristics": [
RuntimeError: Set changed size during iteration
```

This happened while testing something else. Documenting it now so I don't forget

### PR DESCRIPTION
**Pull request by bdraco**
Fixes #85

### CODE REVIEW

**Review by Jc2k — APPROVED** [review]
At the moment there is a lock in the send/recv code path so that only one request is in flight at once. I think because they are sharing a single TCP stream I needed to be sure which response was for which request. There might be a better way to do it but right now the parallelism doesn't help, and probably adds overhead.

So might be just as well turning the iterator into a list and looping over it rather spawning a bunch of tasks to fight over the lock?

**Comment by bdraco** [comment]
I'll change it to pre-build the list of calls instead of the gather

**Comment by Jc2k** [comment]
I'll do a release when I'm near my desk.

**Comment by bdraco** [comment]
@Jc2k -> gentle reminder 👍

**Pull request merged**
