### PR TITLE
Allow passing in a bleak instance

### PR DESCRIPTION
**Pull request by bdraco**

### CODE REVIEW

**Comment by Jc2k** [comment]
With zeroconf we ended up making it the callers responsibility to pass in a Zeroconf instance. Do we want to do that here for symmetry and not have a default?

**Comment by bdraco** [comment]
> With zeroconf we ended up making it the callers responsibility to pass in a Zeroconf instance. Do we want to do that here for symmetry and not have a default?

I'm on the fence.  Maybe we change how this works once we have the COAP done?

**Comment by bdraco** [comment]
Mostly on the fence because beta is Wed and I tend to get more conservative about making changes the closer we get to it.

**Comment by Jc2k** [comment]
Haha fair point!

**Pull request merged**
