### PR TITLE
Handle incomplete ServiceInfo properties in async_find_data_for_device_id

### PR DESCRIPTION
**Pull request by bdraco**
fixes https://github.com/home-assistant/core/issues/45199

### CODE REVIEW

**Comment by bdraco** [comment]
Github is being flakey tonight so I had to close and reopen this as a new PR to get the CI to run

**Review by Jc2k — APPROVED** [review]
This looks great. I'll try and put out a release with it later today.

**Comment by bdraco** [comment]
@Jc2k Hope all is well. Sending a quick reminder about that release. Cheers

**Comment by Jc2k** [comment]
Ah thanks for the reminder! Super busy irl and had totally slipped my mind. Have pushed a tag. Hopefully a pypi release will appear shortly.

**Comment by bdraco** [comment]
Thanks. I'll take care of bumping Home Assistant 👍

**Pull request merged**
