### PR TITLE
Remove stray zeroconf argument

### PR DESCRIPTION
**Pull request by bdraco**
```
2020-07-10 16:03:15 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 136, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 92, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 201, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 275, in async_step_pair
    discovery = await self.controller.find_ip_by_device_id(self.hkid)
  File "/usr/local/lib/python3.7/site-packages/aiohomekit/controller/controller.py", line 92, in find_ip_by_device_id
    max_seconds=max_seconds, zeroconf_instance=self._zeroconf_instance
TypeError: discover_ip() got an unexpected keyword argument 'zeroconf_instance'
```

### CODE REVIEW

**Comment by bdraco** [comment]
Still doing testing.  Will push any additional fixes to this PR and mark it ready for review when everything is TEST PASS

**Comment by Jc2k** [comment]
Cheers @bdraco !

**Comment by bdraco** [comment]
It is taking a while to pair.

**Comment by bdraco** [comment]
Oh, its doing a full discover and never hitting the `async_find_device_ip_and_port` code

**Comment by bdraco** [comment]
When you click configure in home assistant, the device should respond near instantly now

**Comment by Jc2k** [comment]
*happy dance* It's been on my todo list for ages to sort that out so thank you very much!

**Comment by Jc2k** [comment]
Awesome! Thanks for sorting this out.

**Pull request merged**
